name: Déployer en prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: srv-ftp-mail
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /var/www/html/
        remote_host: 51.15.20.131
        remote_port: 2226
        remote_user: pigeon
        remote_key: ${{ secrets.DEPLOY_KEY }}